### ISSUE TITLE
Advantages over other solutions

### ISSUE THREAD

**Issue by ln-12** [tytydraco/LADB#1]
Hey, seems like a nice tool! I just wondered what advantage it has over for example the popular (and free) [Termux](https://github.com/termux/termux-app) app with the [ADB extension](https://github.com/MasterDevX/Termux-ADB). On my OnePlus Nord I can easily find my device via `adb devices -l` in Termux.

**Comment by tytydraco** [comment]
Hi! Thanks for the question. LADB basically bundles the ADB binary compiled by osm0sis into an app that doesn't require much setup. It's essentially the same as running an adb shell with any other tool.
