### ISSUE TITLE
Update notifications for github build?

### ISSUE THREAD

**Issue by e-t-l** [tytydraco/LADB#10]
Is there a good way to get notified when there's a significant enough commit to justify building a new apk? (I know [Newpipe](https://play.google.com/store/apps/details?id=com.draco.ladb&hl=en_US&gl=US) has some code on their github build that pushes notifications to update the app, but I haven't looked through enough of their source to identify where it is, if you were interested in using it.)

**Comment by tytydraco** [comment]
Not sure about this and so sorry for the incredibly late reply. I must have missed the email. I don't have that at the moment but I guess you could always watch for when I do a "Update version code" commit.
