### ISSUE TITLE
Crash on bookmarks opening

### ISSUE THREAD

**Issue by teou1** [tytydraco/LADB#100]
Hi,
After the latest update from yesterday crashes very reliably everytime i click on the bookmarks button. Pixel 4a A13 if that matters.

**Comment by anirov** [comment]
Confirm.
Version 2.2 does not allow you to create a new bookmark.
And, unfortunately, all the bookmarks that I had on version 2.1 are now destroyed.
(Android 8.0, Samsung)

**Comment by teou1** [comment]
With the version from today everything works again, the saved bookmars are also there. Thanks.
