### ISSUE TITLE
Android Studio build error: Failed to apply plugin 'com.android.internal.application'

### ISSUE THREAD

**Issue by e-t-l** [tytydraco/LADB#11]
I just cloned this repo and am trying to build it in Android Studio, but I immediately get this error:
```
Build file 'C:\Users\Elija_000\git\LADB\app\build.gradle' line: 2

An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > java.lang.NoSuchMethodException: java.lang.invoke.MethodHandles.privateLookupIn(java.lang.Class, java.lang.invoke.MethodHandles$Lookup)
```
Any ideas how to fix this? I've tried rebuilding the gradle cache and .gradle folder, and it looks like all the dependencies are up-to-date, but I'm not an expert and I could be missing something.

**Comment by tytydraco** [comment]
Make sure you are using Android Studio Canary!

**Comment by e-t-l** [comment]
Do you know what version(s) are compatible, by any chance? I try not to use the latest canary for big things like AS, just because I don't need the added stress of IDE bugs on top of my regular code bugs.

**Comment by tytydraco** [comment]
Not sure about that one. Try downgrading the gradle versions.
