### ISSUE TITLE
Stored commands

### ISSUE THREAD

**Issue by requa3r0** [tytydraco/LADB#12]
Hi

Do you know ServerAssistant for android?
Here you can send predefined commands to linux severs.

Here you can store commands on server based setup, to re-run commands easy

This would be a nice feature for your app.

Some commands are pretty long, and if you need to re-run them often, its very practical to have them stored.

Kind regards
Requaero

**Comment by tytydraco** [comment]
Thanks! That sounds like a cool idea. I'll look into it in the future :)

**Comment by ksaechao** [comment]
Ditto on this feature.  I currently use the built-in clipboard manager on my Samsung phone, but a custom command list (or, at minimum, a command history queue) would be great!  

Additionally, as ADB shell commands are often used against packages, an ability to select the name of a specific package would make it easier to use.

**Comment by tytydraco** [comment]
Added
