### ISSUE TITLE
Packaging request for alternate Application Markets.

### ISSUE THREAD

**Issue by gitman-2021** [tytydraco/LADB#15]
Hello, 
@tytydraco 
@IzzySoft 

I'm a big fan of FOSS, and it would be very helpful to me and to other FOSS enthusiasts, if you allow this application to be packaged for an alternate FOSS-only Application [Repository ](https://f-droid.org/).

Please note that, this would(and not can/may) put a dent on your Sales of 'LADB' on the Play Store Marketplace.
'LADB' would not be the first app which is Paid on Play Store, but free at F-Droid, like the "[Librera Reader](https://f-droid.org/en/packages/com.foobnix.pro.pdf.reader)", "[OsmAnd+](https://f-droid.org/en/packages/net.osmand.plus)", "[FTP Server](https://f-droid.org/en/packages/be.ppareit.swiftp_free)", and maybe more...

If you do not have any problem with all the above, then please have a look at [this](https://f-droid.org/en/docs/Inclusion_Policy/).

Thanking you...

**Comment by IzzySoft** [comment]
Well, it has an OSI approved license, the code looks "clean" enough (aka no proprietary dependencies) – only the `com.google.android.gms.oss-licenses-plugin` [is a problem](https://gitlab.com/-/snippets/1896503#license-dialogs), as it drags in proprietary dependencies (as all things starting with `com.google.android.` do earlier or later – rather earlier if the package name continues with `gms.`). The link I gave names some alternatives; they are all licensed either Apache-2.0 or MIT and thus could be used in a GPL app AFAIK.

> and maybe more...

May I correct the typo: it's "many more". What jumps to my mind is DAVx5, ICSx5, Conversations … altogether my [app listings](https://android.izzysoft.de/applists) alone have 55 such apps.

<details><summary>paid on Google, free on F-Droid</summary>
<pre><code>+----------------------------------------------------+------------------------------------------+-------------+
| name                                               | package_name                             | price       |
+----------------------------------------------------+------------------------------------------+-------------+
| 9000 Stars Planisphere                             | org.tengel.planisphere                   | 1.2500 EUR  |
| Acode - powerful code editor                       | com.foxdebug.acode                       | 7.0000 EUR  |
| Alarmio                                            | me.jfenn.alarmio                         | 2.0000 EUR  |
| AnonAddy for Android                               | host.stjin.anonaddy                      | 2.5000 EUR  |
| Auto Auto-Rotate                                   | com.jarsilio.android.autoautorotate      | 1.5000 EUR  |
| Autostarts                                         | com.elsdoerfer.android.autostarts        | 1.7500 EUR  |
| BatteryBot Pro                                     | com.darshancomputing.BatteryIndicatorPro | 3.0000 EUR  |
| Contact Diary                                      | com.apozas.contactdiary                  | 1.2500 EUR  |
| Contour lines plugin — OsmAnd                      | net.osmand.srtmPlugin.paid               | 5.0000 EUR  |
| Conversations (Jabber / XMPP)                      | eu.siacs.conversations                   | 3.0000 EUR  |
| DAVx⁵ – CalDAV & CardDAV Sync client               | at.bitfire.davdroid                      | 5.0000 EUR  |
| De-Bloater Pro (ROOT)                              | com.sunilpaulmathew.debloater            | 0.7500 EUR  |
| DecSync CC                                         | org.decsync.cc                           | 5.0000 EUR  |
| Discreet Launcher                                  | com.vincent_falzon.discreetlauncher      | 3.0000 EUR  |
| DSub for Subsonic                                  | github.daneren2005.dsub                  | 3.2500 EUR  |
| Easy Watermark: Free Open Source Offline No Ads    | me.rosuh.easywatermark                   | 1.0000 EUR  |
| Graph 89 - (with TI84 support)                     | com.Bisha.TI89EmuDonation                | 3.2500 EUR  |
| Greentooth                                         | com.smilla.greentooth                    | 1.0000 EUR  |
| ICSx⁵ – Webcal & .ics calendars subscribe          | at.bitfire.icsdroid                      | 2.0000 EUR  |
| Librera PRO - eBook and PDF Reader (no Ads!)       | com.foobnix.pro.pdf.reader               | 3.0000 EUR  |
| Lightning Browser Plus - Web Browser               | acr.browser.lightning                    | 1.5000 EUR  |
| Ltt.rs - Open Source Email client (JMAP)           | rs.ltt.android                           | 1.0000 EUR  |
| microMathematics Plus                              | com.mkulesh.micromath.plus               | 2.2500 EUR  |
| Musical Notes                                      | jl.musicalnotes                          | 5.0000 EUR  |
| News for Nextcloud (unofficial)                    | co.appreactor.news                       | 5.0000 EUR  |
| Nextcloud Bookmarks                                | org.schabi.nxbookmarks                   | 0.7500 EUR  |
| Nextcloud News                                     | de.luhmer.owncloudnewsreader             | 1.0000 EUR  |
| Nextcloud Notes                                    | it.niedermann.owncloud.notes             | 3.0000 EUR  |
| Nextcloud SMS                                      | fr.unix_experience.owncloud_sms          | 1.5000 EUR  |
| Notable Plus                                       | com.icechen1.notable.pro                 | 1.2500 EUR  |
| OkcAgent                                           | org.ddosolitary.okcagent                 | 1.0000 EUR  |
| Opus 1 Music Player                                | de.kromke.andreas.opus1musicplayer       | 0.5000 EUR  |
| OsmAnd+ — Offline Maps, Travel & Navigation        | net.osmand.plus                          | 20.0000 EUR |
| ownCloud                                           | com.owncloud.android                     | 0.7500 EUR  |
| Permission Manager X                               | com.mirfatif.permissionmanagerx          | 1.0000 EUR  |
| Photuris III                                       | xyz.hisname.fireflyiii                   | 3.5000 EUR  |
| Privacy Browser                                    | com.stoutner.privacybrowser.standard     | 1.0000 EUR  |
| qBittorrent Controller Pro                         | com.lgallardo.qbittorrentclientpro       | 2.5000 EUR  |
| Recordatorios en Notificaciones Pro                | de.nproth.pin                            | 0.5000 EUR  |
| Red Moon                                           | com.jmstudios.redmoon                    | 2.5000 EUR  |
| Simple Calendar Pro - Agenda & Schedule Planner    | com.simplemobiletools.calendar.pro       | 1.0000 EUR  |
| Simple Contacts Pro: Address Book & Contact Backup | com.simplemobiletools.contacts.pro       | 1.0000 EUR  |
| Simple File Manager Pro: File Explorer & Organizer | com.simplemobiletools.filemanager.pro    | 1.0000 EUR  |
| Simple Gallery Pro: Video & Photo Manager & Editor | com.simplemobiletools.gallery.pro        | 1.0000 EUR  |
| Simple Notes Pro: To-do list organizer and planner | com.simplemobiletools.notes.pro          | 1.0000 EUR  |
| Smart Receipts Plus                                | wb.receiptspro                           | 16.0000 EUR |
| Terminightor                                       | org.schabi.terminightor                  | 0.7500 EUR  |
| Termux:Boot                                        | com.termux.boot                          | 2.0000 EUR  |
| Termux:Styling                                     | com.termux.styling                       | 2.0000 EUR  |
| Termux:Tasker                                      | com.termux.tasker                        | 2.0000 EUR  |
| Tinc App                                           | org.pacien.tincapp                       | 6.0000 EUR  |
| Trekarta - offline maps for outdoor activities     | mobi.maptrek                             | 0.7500 EUR  |
| Turbo Editor PRO | Text Editor                     | com.maskyn.fileeditorpro                 | 1.5000 EUR  |
| WaveUp Tasker Plugin                               | com.jarsilio.android.waveup.tasker       | 1.5000 EUR  |
| Zandy                                              | com.gimranov.zandy.app                   | 2.0000 EUR  |
+----------------------------------------------------+------------------------------------------+-------------+</code></pre></details>

**Comment by gitman-2021** [comment]
> Well, it has an OSI approved license, the code looks "clean" enough (aka no proprietary dependencies) – only the `com.google.android.gms.oss-licenses-plugin` [is a problem](https://gitlab.com/-/snippets/1896503#license-dialogs), as it drags in proprietary dependencies (as all things starting with `com.google.android.` do earlier or later – rather earlier if the package name continues with `gms.`). The link I gave names some alternatives; they are all licensed either Apache-2.0 or MIT and thus could be used in a GPL app AFAIK.
> 
> > and maybe more...
> 
> May I correct the typo: it's "many more". What jumps to my mind is DAVx5, ICSx5, Conversations … altogether my [app listings](https://android.izzysoft.de/applists) alone have 55 such apps.
> paid on Google, free on F-Droid

Thank you very much for such a quick, helpful, informative and to-the-point reply,

And I'm really sorry for using 
> and maybe more...
without knowing the actual condition...

And may i ask, what all can we do about `com.google.android.gms.oss-licenses-plugin`, or is it just a dialog-box with list of licenses used in the project, as the name suggests ?

Thanking you once again...

**Comment by tytydraco** [comment]
I definitely think putting LADB on FDroid would be a good idea in the future. I'll definitely be considering this for the future.

**Comment by IzzySoft** [comment]
@gitman-2021

> And I'm really sorry for using

Eh, always good to be cautious. Actually, I was rather "playing on your words" and we could meet in the middle, with "several more"; compared to the 3.5k apps on F-Droid or the ~3M apps on G, 55 is a small number :wink:

About that plugin: yes, to my knowledge it just collects the licenses of all used modules and shows them in a view, to give credits. So do the alternatives I point out in my snippet. From what I've heard (I'm no Android dev) it should not be too hard to switch.

@tytydraco glad you like the idea! If you'd provide the APK (e.g. [tag your releases](https://github.com/tytydraco/LADB/releases) and attach it there), I could quickly pick it up and add it to [my repo](https://apt.izzysoft.de/fdroid) until you're ready for "F-Droid proper". The latter would need tags anyway, and my scanner would help prove when it's ready. Further, that way I could help you getting [Fastlane structures](https://gitlab.com/snippets/1895688) ready (so you stgay in control of descriptions, can provide screenshots etc) as I'd set them up on my end anyway :wink:

**Comment by tytydraco** [comment]
I'll have to think about it a bit more first. I'll get back to you if I decide to go through with it!

**Comment by Poussinou** [comment]
Any news about this?

This app clearly has its place on F-Droid :)

**Comment by tytydraco** [comment]
I'm going to be completely transparent and honest with you guys; my main concern is that doing this will hurt profits. I am still a huge believer in the "build it yourself" mentality though. I would rather individuals take the time to learn to compile Android apps on their own than download it on another website. I'm sorry 😔

**Comment by N-X-T** [comment]
> I'm going to be completely transparent and honest with you guys; my main concern is that doing this will hurt profits. I am still a huge believer in the "build it yourself" mentality though. I would rather individuals take the time to learn to compile Android apps on their own than download it on another website. I'm sorry 😔

Hello, I am newbie, i try building this app then open and got this:
What should i do next? Thanks!
![52af74ed-322b-4fba-a4f6-df95423f55d5](https://user-images.githubusercontent.com/49335931/156875421-d7583edb-f2f9-4d7b-b7e5-6f0101e1c31b.jpg)

**Comment by rihaq** [comment]
Then remove the source code too, it will get you more profit

**Comment by megapro17** [comment]
Why are you so greedy? Are you underpaid at work, so you need some a few pennies from the play store?

**Comment by lamyergeier** [comment]
> I'm going to be completely transparent and honest with you guys; my main concern is that doing this will hurt profits. I am still a huge believer in the "build it yourself" mentality though. I would rather individuals take the time to learn to compile Android apps on their own than download it on another website. I'm sorry 😔

@tytydraco: I respect that you would like to be compensated for your hard work, but could you please clarify if it comes at the expense of the privacy of the end user? Or is there any malignant tracker in the app?

**Comment by robin-paulson** [comment]
> Why are you so greedy? Are you underpaid at work, so you need a few pennies from the play store?

Insulting and judging other folks is rarely useful. You could have asked about this in a respectful way.
