### ISSUE TITLE
Enable secure shell

### ISSUE THREAD

**Issue by gaycodegal** [tytydraco/LADB#16]
I wanted to run a permission revoke command from this app and got 'neither user nor current process has android.permission.REVOKE_RUNTIME_PERMISSIONS' for example the command I was trying to run looked like  `pm revoke com.offendingapp
android.permission.INTERNET` there's a secure mode you can run ADB in that allows you to do such things

**Comment by gaycodegal** [comment]
Oh yeah I'm using a non root pixel 3 with the play store version of your app

**Comment by tytydraco** [comment]
Hi! Looks like this is just an issue with the command and not with LADB itself. The reason you see this is probably because you can't revoke internet permissions from an app since they are an implicit permission (not requiring user confirmation).

**Comment by tytydraco** [comment]
Feel free to reopen the issue if you need more help!

**Comment by gaycodegal** [comment]
oh you're right, i hadn't attempted this from the computer, which returns a different message `Permission android.permission.INTERNET requested by com.offendingapp is not a changeable permission type`; I think the point is more that it would be nice if LADB didn't return `neither user nor current process has android.permission.REVOKE_RUNTIME_PERMISSIONS` and instead was able to do the proper command, resulting in the "not changeable" error. That being said, probably not worth fixing
