### ISSUE TITLE
AOSP version S - no return key present on keyboard

### ISSUE THREAD

**Issue by serviceberry3** [tytydraco/LADB#17]
Awesome work. I'm running aosp_flame-userdebug S AOSP.MASTER. When the keyboard pops up to type in shell cmds, there's no return key; in it's place is the emoji keyboard button. This can be fixed by changing ```android:inputType="textNoSuggestions|textShortMessage"``` to  ```android:inputType="textNoSuggestions|text"``` in activity_main.xml, for example.

**Comment by tytydraco** [comment]
Thanks! Could you try testing this change on your device if you haven't already? I can merge it after. I don't own an Android 12 device is the reason.

**Comment by serviceberry3** [comment]
@tytydraco Yup, I tested it

**Comment by tytydraco** [comment]
https://github.com/tytydraco/LADB/commit/3a51f3d5f849671c2be0ec4f94fc062e517c33d4

Problem solved. Thanks for the help!
