### ISSUE TITLE
Stuck at unclickable  wireless option 

### ISSUE THREAD

**Issue by mycal123** [tytydraco/LADB#18]
You can see dialogues. I only turn on when connected to other android

**Comment by mycal123** [comment]
![Uploading IMG_20210610_115213.jpg…]()

**Comment by mycal123** [comment]
![IMG_20210610_115213](https://user-images.githubusercontent.com/59077033/121476375-35f66a00-c9e4-11eb-9a37-5507654e9417.jpg)

**Comment by tytydraco** [comment]
Something tells me you need to be connected to a Wi-Fi network.
