### ISSUE TITLE
Cant type 

### ISSUE THREAD

**Issue by PaqcoFlaco** [tytydraco/LADB#22]
Cant type commands iv tried all the things airplane mode even an apk online instead of playstore cant figure it out still trying though lmk what I can do I'm running android 11 on a tab s6

**Comment by tytydraco** [comment]
Well did everything pair successfully? Show me how you are trying to do the pairing. You can reset by clearing the LADB app data.

**Comment by PaqcoFlaco** [comment]
Yep just go to settings and apps choose LADB then clear data which will
clea both data and cache to restart the process with port and code option
on LADB

**Comment by PaqcoFlaco** [comment]
Lmao okay whatever I did now I can type lol I changed my keyboard is the
only thing jv done in the last 30 min

Thanks lol
