### ISSUE TITLE
Can't install app on Samsung devices from compiled APK file

### ISSUE THREAD

**Issue by pronoymukherjeewritescode** [tytydraco/LADB#26]

**Comment by tytydraco** [comment]
I'm gonna need more information. What did you compile it with, what device did you install it on?

**Comment by Bhavinjain260** [comment]
Or can you make a small section in the readme section 
Which compilor to use etc etc
And simple building steps

**Comment by tytydraco** [comment]
> Or can you make a small section in the readme section
> Which compilor to use etc etc
> And simple building steps

You just need Android Studio Canary. But the compile steps are dead simple, you can find out how online.

**Comment by Bhavinjain260** [comment]
any dependency ?
i tried to build the apk couple of times in that all the time it failed

**Comment by tytydraco** [comment]
> any dependency ?
> i tried to build the apk couple of times in that all the time it failed

Just Android Studio Canary

**Comment by Bhavinjain260** [comment]
![Screenshot 2021-07-16 at 11 21 36 PM](https://user-images.githubusercontent.com/49932650/125988944-6181fca1-87d8-40d0-bfba-ee37e2517d11.png)
mind helping me ?

**Comment by Bhavinjain260** [comment]
NM somehow build the apk

**Comment by tytydraco** [comment]
> ![Screenshot 2021-07-16 at 11 21 36 PM](https://user-images.githubusercontent.com/49932650/125988944-6181fca1-87d8-40d0-bfba-ee37e2517d11.png)
> mind helping me ?

You need to accept the sdk licences

**Comment by pronoymukherjeewritescode** [comment]
> I'm gonna need more information. What did you compile it with, what device did you install it on?

I installed on Galaxy Tab A 10.1 & compiled it using the Android-SDK Tools & Gradle...

**Comment by pronoymukherjeewritescode** [comment]
But the weird thing is the APK works on other, non-samsung devices

**Comment by tytydraco** [comment]
> But the weird thing is the APK works on other, non-samsung devices

Hmm, I'm not entirely sure then. If you could compile the apk then you should be all set. I'd guess it's a device issue?

**Comment by secchipietro04** [comment]
i managed to make it work by going File | Settings | Appearance & Behavior | System Settings | Android SDK | SDK tools, install "Android sdk command-line tools".
It will download and install it and asks to accept licences, then all worked perfectly
