### ISSUE TITLE
[Feature Request/Idea] LADB File explorer

### ISSUE THREAD

**Issue by Gnomey123** [tytydraco/LADB#29]
I'm aware of the time and complexity this would take to achieve (as you can't slap on something like [AmazeFileManager](https://github.com/TeamAmaze/AmazeFileManager) and call it a day :P ), But I really see potential here.

The idea came from when I was trying to view my OOS Logkit files, to only then find myself booting up my pc and pulling the files myself.

I don't believe that LADB necessarily needs this feature, as it's nearly a convenience of life that's worth the premium for power users (anyone can use Terminix after all).

However, a file manager that utilizes ADB would be the most powerful on the market. I can see not just power users but the average person using a utility like this to mod an app or such.

Beyond files, useful ADB commands have been documented since the beginning of Android. I definitely see potential with LADB, and I'm happy to support FOSS developers.

**Comment by tytydraco** [comment]
This is an excellent idea. I'll certainly look into seeing if this is doable. The issue I see is that SAF won't let us pick a path that we aren't supposed to use, so I'll have to resort to raw access. But I have an idea that might make it work: symlinking. I'll see if I can get it working! Thanks for the idea, I appreciate it. Hopefully it works out.

**Comment by tytydraco** [comment]
Looks like this is a bit too hard to implement as of now, it would be a new app. But still, good idea!
