### ISSUE TITLE
(Feature Request) "Execute" shortcuts

### ISSUE THREAD

**Issue by GL513** [tytydraco/LADB#30]
App shortcuts to execute command, and return error with toast when wifi isnt connected. You can turn on wifi adb woth the secure setting `adb_wifi_enabled` which you can toggle yourself after the app granting itself access to `android.permission.WRITE_SECURE_SETTINGS`
Thanks for letting us provide feedback, Tyler 👍

**Comment by tytydraco** [comment]
Interesting, didn't know that you could enable it via secure settings! I'll look into this :D

**Comment by tytydraco** [comment]
Added!
