### ISSUE TITLE
[Community] Documentation Website - Discord Server

### ISSUE THREAD

**Issue by GL513** [tytydraco/LADB#32]
For this, you can use mkdocs. as far as i know, material docs by squidfunk is the best one. you can build it yourself really quickly, and if you really want, when im done with my own i can fork it and modify the color scheme to match  LADB's. You could put things here like tutorials, and link to communications. 
outside of that, i think it would be nice to have a discord so we can chat, talk about LADB, and share tricks and ADB commands that are useful. If you like, I can help with moderating. If you arent sure about me doing that, it might help by saying that I moderate the [KeyMapper](https://play.google.com/store/apps/details?id=io.github.sds100.keymapper&hl=en_US&gl=US) server, but i understand if you still dont want me to.

**Comment by tytydraco** [comment]
https://t.me/ladb_support

Here's the official telegram server!
