### ISSUE TITLE
libadb compile

### ISSUE THREAD

**Issue by GG-coder889** [tytydraco/LADB#39]
Could you tell me how can I build the libadb library, Thanks

**Comment by vullnetlimani** [comment]
That would be great since I want to have Version 31.0.3-7562133

**Comment by tytydraco** [comment]
It's surge's and osm0sis' binary, so we don't build from source here. You would have better luck contacting them and seeing if they would be happy enough to give you the source :D

**Comment by hhhaiai** [comment]
@tytydraco   

It's surge's and osm0sis' binary, so we don't build from source here. You would have better luck contacting them and seeing if they would be happy enough to give you the source :D


where's the address?

**Comment by hhhaiai** [comment]
https://github.com/Surge1223/adb-arm-1.0.37

this？  @tytydraco

**Comment by tytydraco** [comment]
> https://github.com/Surge1223/adb-arm-1.0.37
> 
> this？ @tytydraco

Well that was updated 4 years ago so that isn't it. It's probably not open source. But that's the right guy who built it. Maybe there's an email.

**Comment by hhhaiai** [comment]
>ok。 thx
