### ISSUE TITLE
adb: unknown command pair

### ISSUE THREAD

**Issue by Corecii** [tytydraco/LADB#42]
On my Samsung Tab A 10.1 2019 (Android 11) I get `adb: unknown command pair` when attempting to pair LADB with the device.

<details><summary>Screenshots</summary>

![Screenshot_20211024-002609_LADB](https://user-images.githubusercontent.com/1669436/138582344-1485ffea-6aeb-47d3-bcc4-792d84a70fa5.jpg)
![Screenshot_20211024-002620_LADB](https://user-images.githubusercontent.com/1669436/138582345-003435ac-8bc1-4717-a0a5-dfea718c4ec9.jpg)

</details>

**Comment by lilkidsuave** [comment]
Same here

**Comment by njosey** [comment]
Also have the same issue,

I don't know why it's literally not recognizing the most vital command since the app won't work without it

**Comment by jaajko** [comment]
also having this issue

**Comment by tytydraco** [comment]
Looks like this is due to the 32-bit libadb binary not being updated for the new pair feature. Sadly I don't maintain the binary itself, just the app that uses it. In the meantime, anyone who has purchased LADB on Android 11+ on a 32-bit device having this issue can get a refund, just email me at tylernij@gmail.com with your order ID from payments.google.com. Sorry folks 🤕❤️

**Comment by njosey** [comment]
Pretty sure I have aarch64 which I have confirmed with the cpu z app and I'm pretty sure aarch64 is 64 bit

So this issue is not just on "32 bit devices"

https://en.m.wikipedia.org/wiki/AArch64

Unless your app is for some reason exclusively using the 32 bit library

**Comment by tytydraco** [comment]
> Pretty sure I have aarch64 which I have confirmed with the cpu z app and I'm pretty sure aarch64 is 64 bit

Remember that the CPU might be 64 bit but the OEM may provide a 32 bit rom. Double check getprop abis.

**Comment by njosey** [comment]
> > Pretty sure I have aarch64 which I have confirmed with the cpu z app and I'm pretty sure aarch64 is 64 bit
> 
> Remember that the CPU might be 64 bit but the OEM may provide a 32 bit rom. Double check getprop abis.

I checked that using adb on termux since ladb is obviously not working using the command "adb shell getprop ro.product.cpu.abilist"

It returns

arm64-v8a
armeabi-v7a
armeabi

If I'm right the rom appears to be 64 bit

**Comment by njosey** [comment]
AIDA64 also says 64bit and according to this article it says it based that on the Android and not the hardware

https://nerdschalk.com/32-bit-and-64-bit-android-phones-list/amp/

**Comment by tytydraco** [comment]
Hmm, well if you are for-sure on a 64-bit rom, have you made sure you're also for-sure on the latest LADB build? I think like, 6 months ago I updated the binary that fixed this issue, so maybe if your version is old enough, it could explain the issue. 

Also, do you have adb built into the system? For example, if you type "which adb", do you get a valid path, or just "not found"?
