### ISSUE TITLE
Connect LADB via Notification Panel

### ISSUE THREAD

**Issue by ankitvrsharma** [tytydraco/LADB#43]
Can you add option to connect to wireless adb via Notification Panel like Shizuku added in their last update.

**Comment by GL513** [comment]
i think it would be better to just have the application use a shortcut, like you might use Tasker to launch an application shortcut, and then use automation apps like tasker and Automate to launch it from there

**Comment by tytydraco** [comment]
If I did this it would just be a shortcut to the app. I guess I could add it though.

**Comment by tytydraco** [comment]
Added in https://github.com/tytydraco/LADB/commit/0204e5bbec69eedf13cca66c7fc69b971736c00e
