### ISSUE TITLE
Not working in Android 12

### ISSUE THREAD

**Issue by amrathesh** [tytydraco/LADB#44]
Shows successful pairing but doesn't open ADB shell, app used to work fine with Android 11.
![Screenshot_20211110-200225~2](https://user-images.githubusercontent.com/48640575/141133318-baa20de8-0646-4d9a-918b-38efbc7bb296.png)

**Comment by e-t-l** [comment]
LADB is working fine on my Pixel 3 (unrooted) running Android 12. Can you provide nor einfo on your setup?

**Comment by TheBSGamer** [comment]
I'm having this issue as well. I'm on a Galaxy S21 Ultra running the latest OneUI 4.0 update. Uninstalled the app and reinstalled with no difference. It worked previously on OneUI 3.1 for me. Not sure what I'm doing wrong. I enter the pairing code and port and get that successful message, then just nothing happens except for the loading icon.

**Comment by tytydraco** [comment]
Very interesting, I've been getting a bunch of reports like these recently and I'm not sure why. I will check if any of my devices have this issue tonight after I finish studying. People usually seem to fix this by force closing LADB and opening it again. I think the issue is that LADB isn't detecting the device as paired even though it is, so it just stalls. I will fix this <3

**Comment by TheBSGamer** [comment]
No worries. Thank you for your hard work!

If you need anything else from me, just let me know.

**Comment by tytydraco** [comment]
Hopefully fixed in these commits:

0771eabd8eb3fac6669ad0f1494771f7424086ac
6257843a1313c523a952993d0e6ec981c6b479f0

Let me know if that fixed it for you. @TheBSGamer

**Comment by TheBSGamer** [comment]
I might be a little naive, how can I test? Do I need to compile it? Sorry 😅

**Comment by tytydraco** [comment]
It'll update on gplay in a day or less, or you can compile. Either work

**Comment by TheBSGamer** [comment]
Okay. I'll wait for the update as I've never compiled an APK before.

**Comment by TheBSGamer** [comment]
Hey @tytydraco, just got the update and that did the trick! Thank you!

**Comment by amrathesh** [comment]
Thank you @tytydraco.
