### ISSUE TITLE
[SOLVED] "Enter pairing code: Failed: Unable to start pairing" immediately

### ISSUE THREAD

**Issue by woody4165** [tytydraco/LADB#46]
Hi

I followed all the tutorials on README page here and on the Help in the app, but I get the "Enter pairing code:" message, I get immediately the error "Failed: Unable to start pairing" suddenly" and I don't have the time to write the code.

If I enable the Airplane Mode, as in the Troubleshooting section, I get the error that the app is not licensed.

What else can I check?

I am on a Xiaomi Redmi Note 10s with latest 12.5.14 not rooted

Thanks

**Comment by tytydraco** [comment]
Hey! I would guess that maybe the pairing code / port are malformed or wrong. Remember that if you do not use split screen, the code will change as soon as the settings app is not in the foreground anymore. If you can, maybe attach a screenshot of what you're entering in the port and pairing code fields.

**Comment by woody4165** [comment]
Thanks
I found also a youtube video, and it works.

**Comment by Dashhamada** [comment]
> Thanks I found also a youtube video, and it works.

I have tha same issue, whare is this video please?

**Comment by RAMKALYA** [comment]
Failed: Unable to start pairing client  plz solve this problem.

**Comment by DxBONESxBACK** [comment]
If both windows are open (settings/developer options/wireless debugging & LADB app) as needed and you are getting this error make sure that you don't have anything like Don't keep activities, strict mode, or the background processing limit set low(lower than default). I had the same issue with one of my Android devices and after reinstalling LADB then without attempts of connecting it I rebooted and was successfully connected.
