### ISSUE TITLE
Limited maximum output character/line limit? 

### ISSUE THREAD

**Issue by e-t-l** [tytydraco/LADB#48]
Is there a limit to the maximum length of the output LADB displays?

I'm having trouble getting LADB to display output longer than 7982 characters / 302 lines. This is specifically a problem when users try to run the (fairly commonplace) command `pm list packages`.

**Comment by tytydraco** [comment]
You can try piping it out to a file and then opening that in a file manager. There is a max limit, too many characters causes some serious lag.
