### ISSUE TITLE
[Enhancement] Option to automatically enable WiFi Debug when LADB launches

### ISSUE THREAD

**Issue by e-t-l** [tytydraco/LADB#49]
Since apps are able to write the system setting `[Global]  adb_wifi_enabled(1)` It would be nice if there were an option IN LADB to activate wifi debugging automatically on launch, so users don't have to go into Dev Settings and turn it on manually.

(It would also be good for LADB to then set `[Global]  adb_wifi_enabled(0)` upon exit, but I'm not sure how this would be accomplished without a persistent background service to monitor LADB's running status. Such a service could kill itself right after it sets the system setting, and if it's only triggered by LADB's launch, it shouldn't be a drain on phone resources, but background services are beyond my ability to code).

I'm not familiar with using Kotlin as it is, but if this sounds like a feature you'd be interested in adding, I can take a look and see how far I can get in a new branch.

**Comment by tytydraco** [comment]
This is a good idea! I can look into this feature.

**Comment by tytydraco** [comment]
Added in https://github.com/tytydraco/LADB/commit/f4eaf469e596498eba7ea0117d668b836b9859b2
