### ISSUE TITLE
Wireless Debuging auto off,doesn't show the port code.

### ISSUE THREAD

**Issue by dnguyen2603** [tytydraco/LADB#50]
Help me, my Samsung A20s in wireless debug, it doesn't show the port code. Only turns on for more than 5 seconds then turns off automatically
![Screenshot_20211205-232356_Settings](https://user-images.githubusercontent.com/95582792/144755536-580fc5ce-d6f9-4946-9baf-2e26572e7eaa.jpg)

**Comment by tytydraco** [comment]
Hello, this seems to be an issue with the OEM software. Are you on Android 11? Or is this Android 10? Maybe that's why.

**Comment by dnguyen2603** [comment]
Android 11
One Ui Core 3.1

Vào 05:37, T.2, 6 Th12, 2021 Tyler ***@***.***> đã viết:

**Comment by tytydraco** [comment]
Maybe it's just 5555?

**Comment by Missmeanass1970** [comment]
I am using Android 11, and the LADB with wireless debugging will not get past the waiting for device respond. How can I fix this, so I can use the LADB app?

**Comment by kenggame** [comment]
thank you

**Comment by tytydraco** [comment]
I assume this is fixed, if not reopen.
