### ISSUE TITLE
Split screen issue

### ISSUE THREAD

**Issue by iamajraj** [tytydraco/LADB#51]
How can I connect if I don't have split screen option, the pairing key is changing every time I close the settings.
Please do something!

**Comment by qinlili23333** [comment]
Some device can enable `Enable freeform windows` feature in `Developer options`, then u can just run app in window mode like ur desktop PC

**Comment by iamajraj** [comment]
@qinlili23333 I did it but doesn't seem to be work

**Comment by qinlili23333** [comment]
> @qinlili23333 I did it but doesn't seem to be work

u may need to reboot after switch this option on

**Comment by tytydraco** [comment]
I'd that still doesn't work, just use the tcpip 5555 method.
