### ISSUE TITLE
fun abiUnsupportedDialog

### ISSUE THREAD

**Issue by dadaewq** [tytydraco/LADB#54]
[BuildConfig.VERSION_CODE >= Build.VERSION_CODES.R](https://github.com/tytydraco/LADB/blob/669a692282de62d92de4bf42db58d6f3aed29e63/app/src/main/java/com/draco/ladb/viewmodels/MainActivityViewModel.kt#L55)

Build.VERSION.SDK_INT ?

**Comment by tytydraco** [comment]
I'm an idiot. Fixed. This is why I love FOSS stuff, you guys catch my mistakes <3
