### ISSUE TITLE
[Enhancement] Plugin like API for other apps

### ISSUE THREAD

**Issue by NonstickAtom785** [tytydraco/LADB#58]
[Universal Android Debloater](https://github.com/orgua/universal-android-debloater-UI)

So I'm thinking of making an app that allows for a full ADB Debugging GUI application from Android. But I want to first know if it's possible to call on LADBs connection to the local host. As you have worked really hard to make this app I don't want to push people away from using it. I want to encourage the usage and also possibly develop a plugin application. The link above is a gui which supports linux that I want to port to android to make the first actual gui to support non-rooted users. It would be nice to have an app like this that could use LADB to allow full user control without a PC. One of them things that you would see on an XDA Developers headline lol. I don't think I could do this alone though. And I would like to know if you think this is feasible. I want to keep it open source which is why I'm sending a github issue instead of an email.

**Comment by tytydraco** [comment]
I think Shizuku already does a better job at this honestly. It's more built for keeping a session alive like this. LADB closes it's session when the user closes the app, and an API would need to repair the device again. But thank you for this idea! :)
