### ISSUE TITLE
Android 9 ladb can't use 

### ISSUE THREAD

**Issue by kenggame** [tytydraco/LADB#65]
![Screenshot_2022-03-22-01-48-43-76_35b31e89a11164259efde80655844a59](https://user-images.githubusercontent.com/101648722/159343416-05981633-8fad-425c-bb83-f5ef956262f7.jpg)

**Comment by N-X-T** [comment]
LADB need Wireless Debugging to Pair with devices. This feature is only available on android >11.

**Comment by shirooo39** [comment]
> LADB need Wireless Debugging to Pair with devices. This feature is only available on android >11.

if your ROM does not support Wireless ADB out of the box, you could manually make it to listen on wireless mode instead by using this command  

`` adb tcpip 5555 ``

which... you'd need to first execute it on a PC...

**Comment by N-X-T** [comment]
> 

if use "adb tcpip 5555", u need run again after each of reboot and this is annoying :V

**Comment by N-X-T** [comment]
> > LADB need Wireless Debugging to Pair with devices. This feature is only available on android >11.
> 
> I believe Wireless ADB has been around since 4.4 but if your ROM does not support Wireless ADB out of the box, you could manually make it to listen on wireless mode instead by using this command
> 
> `adb tcpip 5555`
> 
> which... you'd need to first execute it on a PC...
> 
> Any custom ROM should at least have this feature baked in, doesn't matter which version (but just to be safe, it's there on >= 8.1)

if use "adb tcpip 5555", u need run again after each of reboot and this is annoying :V

**Comment by shirooo39** [comment]
> if use "adb tcpip 5555", u need run again after each of reboot and this is annoying :V
get a custom rom then. simple as that

**Comment by mirh** [comment]
Can this be closed then, assuming it was just a clueless user at most mislead by the old UI?

**Comment by mirh** [comment]
Actually, I feel like the `tcpip` thing should be also mentioned in the readme.

**Comment by tytydraco** [comment]
> Actually, I feel like the `tcpip` thing should be also mentioned in the readme.

Yes good point. I'll update the README.

**Comment by mirh** [comment]
Seems like it has actually regressed in informativeness?

**Comment by tytydraco** [comment]
> Seems like it has actually regressed in informativeness?

https://github.com/tytydraco/LADB/commit/7025455867bb782c43c4b7926968cd1e35a07154

**Comment by tytydraco** [comment]
Ahhh gotcha
