### ISSUE TITLE
Enter pairing code: Successfully paired to localhost

### ISSUE THREAD

**Issue by nicolai1905** [tytydraco/LADB#69]
Enter pairing code: Successfully paired to localhost:400...........
At this point the page still loading, I did reset 5 times nothing helps.
Please fix it ...
My phone s22ultra last update (may security patch)

**Comment by ntelas** [comment]
1. Force stop LADB
2. Enable flight mode on the device
3. Disable flight mode on the device
4. Open Wireless debugging settings and re-enable it
5. Approve wireless debugging access for the connected Wi-Fi (This prompt was previously not displayed, thus preventing LADB from connecting)
6. Open LADB
7. It should now connect

**Comment by tytydraco** [comment]
Hopefully this has been fixed by a recent update. If not, reopen this issue.
