### ISSUE TITLE
"This app is not licensed."

### ISSUE THREAD

**Issue by gdneye** [tytydraco/LADB#71]
Hello, 

This is my first time building an Android App from source,  but i was able to find a couple of guides, and everything seemed to be working perfectly until I opened the app on my phone. 

When I opened it,  I received the attached error.   Googling the error code didn't pull much up. 

There is no option that allows me to get beyond this screen.  Clicking close minimizes the app and the warning returns and I switch back to the app.  I've also tried closing the app, force closing the app, rebooting and uninstalling and re-installing.

Nothing has resulted in any change. 
![Screenshot_20220605-080215_LADB](https://user-images.githubusercontent.com/26702989/172051854-b5e7e53c-19d5-46bc-a603-39c88115ddf3.jpg)

**Comment by tytydraco** [comment]
Ah! I see. You can compile the app as debug if you want to dismiss this message, or look for the piracy checker code and just comment it out. I have it off for debug builds and on for release builds. Reopen this issue if it's still an issue.

**Comment by Dhyfer1** [comment]
@gdneye Can you tell me how you compiled the app? I don't have a way to pay for ladb and the only legal way to get it for free is to compile the app, but I don't know how to do it. You can help me?

**Comment by tahayaseenp** [comment]
@Dhyfer1 follow this guide
https://github.com/openaps/AndroidAPSdocs/blob/master/docs/EN/Installing-AndroidAPS/Building-APK.md

**Comment by tahayparker** [comment]
@Dhyfer1 here's a guide
https://github.com/openaps/AndroidAPSdocs/blob/master/docs/EN/Installing-AndroidAPS/Building-APK.md

**Comment by Dhyfer1** [comment]
> @Dhyfer1 here's a guide
> https://github.com/openaps/AndroidAPSdocs/blob/master/docs/EN/Installing-AndroidAPS/Building-APK.md

@tahayparker Thanks for the link. Seems like a very detailed guide. I haven't tried it yet to compile ladb, have you?

**Comment by tahayparker** [comment]
i did, but then didnt find any use for ladb plus ran out of storage so deleted it

**Comment by Dhyfer1** [comment]
Ok. So this guide is also useful for compiling any app that has its source code on GitHub?  And after you compiled ladb, you didn't have the same problem of this issue?

**Comment by tahayparker** [comment]
> So this guide is also useful for compiling any app that has its source code on GitHub?
maybe. no idea tho, never tried with any other apps. dont use my phone much, just for calls, whatsapp and photos, so im not really into this scene.

> And after you compiled ladb, you didn't have the same problem of this issue?
i did, which is why im here. saw your message didnt have any replies (rude tbh) and decided to help out a comrade. bet you didnt expect a reply after 3 months did ya?

**Comment by Dhyfer1** [comment]
> maybe. no idea tho, never tried with any other apps. dont use my phone much, just for calls, whatsapp and photos, so im not really into this scene.

Ok. Then I would have to try.

> i did, which is why im here. saw your message didnt have any replies (rude tbh) and decided to help out a comrade.

Thx. So, in your case. Were you able to solve the same problem mentioned in this issue? And how did you solve it? 

...bet you didnt expect a reply after 3 months did ya?

Not really. Thanks for answering my question after 3 months. In other repositories where I have left questions I am still waiting for a response, but I know it's a combination of luck and patience for someone to answer me, or just not have any answer.

**Comment by tahayparker** [comment]
> Were you able to solve the same problem mentioned in this issue? And how did you solve it?

yeah i just complied it as debug, didnt wanna search through the code to find anti-piracy stuff. kinda lazy to do that

also, can you share some of the apps you're trying to compile? it'd be fun to do stuff, kinda bored rn

**Comment by Dhyfer1** [comment]
> yeah i just complied it as debug, didnt wanna search through the code to find anti-piracy stuff. kinda lazy to do that

I got it, so you did what the dev suggested a few comments above. Ok

> also, can you share some of the apps you're trying to compile? it'd be fun to do stuff, kinda bored rn

Sure. The dev has some open source applications in the Play store, such as [Purr](https://play.google.com/store/apps/details?id=com.draco.purr), [PowerButtonSettings](https://play.google.com/store/apps/details?id=com.draco.powerbuttonsettings), [Ease](https://play.google.com/store/apps/details?id=com.draco.ease), [AnyAssistant](https://play.google.com/store/apps/details?id=com.draco.anyassistant), [Cachie](https://play.google.com/store/apps/details?id=com.draco.cachie) etc
