### ISSUE TITLE
Control-C  Is there a way?

### ISSUE THREAD

**Issue by uglygus** [tytydraco/LADB#72]
Is there some way to exit a running shell command?  I can't find a way to send signals or Control-C.

**Comment by teou1** [comment]
I have tried to, there is no way. I either do not make loops in scripts or close ladb and reopen, or use termux.

I actually think that is a good suggestion for the future: just give us the good old terminal prompt, no need from this input row. It make problems like popping the keyboard by loops all the time and decreasing the visible space (try this)
`while true; do dumpsys battery; sleep 5; done`
And as mentioned, if it was just a terminal one could install hacker keyboard and easily breaking the loop with ctrl c.

**Comment by tytydraco** [comment]
This is a good idea, I believe I tried this before but it wasn't successful. Let me try this again.

**Comment by tytydraco** [comment]
Turns out this is not possible because the ADB process is the only thing we have a handle on, not the subprocesses in the interactive shell
