### ISSUE TITLE
First time setup improvements

### ISSUE THREAD

**Issue by mirh** [tytydraco/LADB#75]
- [ ] It is my understanding that `Settings.Global.ADB_WIFI_ENABLED` can programmatically detect what it has written on the tin
  * [ ] I [believe](https://old.reddit.com/r/androiddev/comments/j6p8q4/wireless_debugging_in_android_11_off/gte71jd/) the WRITE_SECURE_SETTINGS permission could also allow for that to be started automatically
- [ ] none of that is going to be a thing [before](https://android.googlesource.com/platform/frameworks/base/+/2076c04333781235021369d10752c22ff6bf8ced) 11, but for starters you could at least check the normal ADB_ENABLED property
- [x] improve the "waiting for device respond" line, that leaves clueless users like in https://github.com/tytydraco/LADB/issues/65

**Comment by nilsingha112** [comment]
Enter pairing code: failed to parse address

**Comment by tytydraco** [comment]
> * [ ]  It is my understanding that `Settings.Global.ADB_WIFI_ENABLED` can programmatically detect what it has written on the tin
>       
>       * [ ]  I [believe](https://old.reddit.com/r/androiddev/comments/j6p8q4/wireless_debugging_in_android_11_off/gte71jd/) the WRITE_SECURE_SETTINGS permission could also allow for that to be started automatically
> 
>     * [ ]  none of that is going to be a thing [before](https://android.googlesource.com/platform/frameworks/base/+/2076c04333781235021369d10752c22ff6bf8ced) 11, but for starters you could at least check the normal ADB_ENABLED property
> 
>     * [x]  improve the "waiting for device respond" line, that leaves clueless users like in [Android 9 ladb can't use  #65](https://github.com/tytydraco/LADB/issues/65)

Very very true, I will have it not toggle the state for A10 and below! And I will implement those other changes as well.

**Comment by tytydraco** [comment]
Added

**Comment by mirh** [comment]
Nothing of what I left unchecked seems to have happened actually.

**Comment by tytydraco** [comment]
> Nothing of what I left unchecked seems to have happened actually.

I already had the auto wireless debugging thing in a previous update. And I made sure that it only happens on Android 11+. And I added a little note in the new update for more details about the waiting screen. I think that's what you meant right?

**Comment by mirh** [comment]
Duh, I see #49 now sorry. 
Idk why I started talking/worrying about A11 when my phone didn't even have it. 

I think you are still missing the super dumb ADB_ENABLED check though.

**Comment by tytydraco** [comment]
> Duh, I see #49 now sorry. Idk why I started talking/worrying about A11 when my phone didn't even have it.
> 
> I think you are still missing the super dumb ADB_ENABLED check though.

Ah right. Does this actually enable USB debugging when you set the global setting? I know some stuff it doesn't actually toggle.

**Comment by mirh** [comment]
https://stackoverflow.com/questions/11314145/looking-to-enable-and-disable-toggle-adb-or-usb-debugging-using-command-line-o
It should AFAICT, but you need some unclear special permission to modify the setting. Unclear if it couldn't even just be the usual WRITE_SECURE_SETTINGS. 
Nevertheless at least the check should be always possible.

**Comment by tytydraco** [comment]
> https://stackoverflow.com/questions/11314145/looking-to-enable-and-disable-toggle-adb-or-usb-debugging-using-command-line-o It should AFAICT, but you need some unclear special permission to modify the setting. Unclear if it couldn't even just be the usual WRITE_SECURE_SETTINGS. Nevertheless at least the check should be always possible.

https://github.com/tytydraco/LADB/commit/f10143fb90f6aaa7515a983c9e98f2f24235c868

Looks good?

**Comment by mirh** [comment]
Looks gucci to me, even though I didn't personally test it.
