### ISSUE TITLE
Why not using an ADB implementation like Dadb?

### ISSUE THREAD

**Issue by sharpordie** [tytydraco/LADB#78]
I wanted to ask you why you don't use an ADB implementation for LADB? Is it really better to use a binary compiled by "a guy" and that is only compatible with some ARM processors?

I am concerned about the security aspect and I would like to know if there are real benefits over libraries like Dadb?

**Comment by teou1** [comment]
https://github.com/mobile-dev-inc/dadb - it looks very interesting indeed.

2 notes however: at the time ladb started, dadb was still not born, so there wasn't really a choice back then. And the guy that compiled the adb binary back then 2 years ago is a more than respectable developer with a reputation, he is not "some guy", he is working on the things and roms at low level so i wouldn't worry about virus in the binary. I had the same concerns and i did my own little research.

**Comment by tytydraco** [comment]
DADB is cool but for now sadly, it does not support Android 11's pairing mechanism yet. Let's reopen this issue when that functionality gets added. But it is very promising!
