### ISSUE TITLE
Reset connection without deleting the bookmarks

### ISSUE THREAD

**Issue by eloraby** [tytydraco/LADB#81]
The wifi ADB needs a reset every time I restart the device. THe solution is to do a factory reset and reenter the port and wifi code, but I also lose the bookmarks in the process.
Would it be possible to allow reseting the connection information without losing the bookmarks?

**Comment by ShadowFlare** [comment]
It used to leave alone those. I don't know why this was changed to do this.

**Comment by tytydraco** [comment]
Ah I see! This will be fixed.

**Comment by tytydraco** [comment]
Fixed
