### ISSUE TITLE
Connecting to wireless debugging

### ISSUE THREAD

**Issue by IeFHC233** [tytydraco/LADB#85]
I can't connect, it keeps showing that the wrong code, for example schuziku connected

**Comment by teou1** [comment]
The most common errors that i personally made X times are the wrong ports - the pairing service runs on its own port.

And the most important - everythime you minimise the settings, it generates a new code. So the only way to make it work is to split screen and have both settings pin and ladb at the same time

**Comment by IeFHC233** [comment]
I did it but it still shows bad code, I use other applications that need wireless debugging access and it works.
I use screen split

**Comment by tytydraco** [comment]
> 

Do you have something like Shizuku installed? It will conflict with LADB as of now.

**Comment by IeFHC233** [comment]
> > 
> 
> Do you have something like Shizuku installed? It will conflict with LADB as of now.

I just had shizuku but I turned it off but it doesn't help

**Comment by IeFHC233** [comment]
> > 
> 
> Do you have something like Shizuku installed? It will conflict with LADB as of now.

I just had shizuku but I turned it off but it doesn't help

**Comment by tytydraco** [comment]
> 

It needs to be disabled and then you need to reboot. And you may need to remove the wireless debugging connections for it. It is unfortunate but they conflict as of now.

**Comment by IeFHC233** [comment]
![IMG_20221015_223949.jpg](https://user-images.githubusercontent.com/110041677/196006697-6aa9ca71-30c3-43b2-8c6c-ee4f162e612a.jpg)
I did and nothing, I gave some good codes (this is next to the qr code option) and nothing, still shows me that wrong pairing command

**Comment by IeFHC233** [comment]
![IMG_20221015_223949.jpg](https://user-images.githubusercontent.com/110041677/196006697-6aa9ca71-30c3-43b2-8c6c-ee4f162e612a.jpg)
I did and nothing, I gave some good codes (this is next to the qr code option) and nothing, still shows me that wrong pairing command

**Comment by tytydraco** [comment]
Okay well you're on an old and probably pirated version, that's why it's not working.

**Comment by IeFHC233** [comment]
Once LADB was free (promotion for just a few days) and I took it on an account that I no longer use. I did not pirate this application, it is the original one from the Play Store, only from another account

**Comment by tytydraco** [comment]
> Once LADB was free (promotion for just a few days) and I took it on an account that I no longer use. I did not pirate this application, it is the original one from the Play Store, only from another account

Ahh, send me your order ID or original email for it and I'll send you a promo on your other code. Make sure you email it to me though: tylernij+LADB@gmail.com, make the subject like "Transfer purchase"

**Comment by IeFHC233** [comment]
And where can I find the order id by e-mail I didn't get anything because it was actually free

**Comment by tytydraco** [comment]
> And where can I find the order id by e-mail I didn't get anything because it was actually free

Ah right. Okay just email me then so I can send you a promo code

**Comment by IeFHC233** [comment]
Thanks, tomorrow I will be connected to wifi, I will tell you if it works

**Comment by IeFHC233** [comment]
Thanks, it works

**Comment by IeFHC233** [comment]
If you could, you can transform it the command that will work with


Post in thread 'Set automatic lock delay on android to more than 30 min. with ADB' https://forum.xda-developers.com/t/set-automatic-lock-delay-on-android-to-more-than-30-min-with-adb.3791042/post-81421129

I did not want to set it for more than 30 minutes, just change it to 0 because they removed the option in the settings in android 12 realme ui3
