### ISSUE TITLE
Libadb.so update

### ISSUE THREAD

**Issue by teou1** [tytydraco/LADB#87]
Hey, i see you are using the very first available arm version compiled from Osmosis in the magisk repo 2 years ago (i was so thankful for it back then, after i learned that for cross compiling i need smth like Xeon with 32G ram and 500GB source code :) ) . 

It seems things have moved a bit in these 2 years. There is a newer version in Termux in the android-tools package, and there is even newer and very current version from rendiix here 

https://github.com/rendiix/termux-adb-fastboot

I think it's worth replacing, maybe will fix some weird problems with newer phones.

P.s. maybe you want to close/delete some issues to, from the 30 open probably 20 are spam or people that do not read the manual...

**Comment by tytydraco** [comment]
I'll check later today but are these binaries statically compiled? Aka, can we just pop them in without a Termux environment? This is something I've been looking for for a long time 😉

**Comment by tytydraco** [comment]
Update: They are dynamically linked. We need a statically linked binary or a binary that was compiled with the NDK, which is why this is so hard :((

**Comment by tytydraco** [comment]
Update 2: Wait, they are linked against /system/bin/linker64, this might work. Let me try it right now

**Comment by tytydraco** [comment]
Oh boy oh boy it works.
